In [2]:
# import Librairies
import pandas as pd 
import matplotlib.pyplot as plt

# Data & Clean
df = pd.read_csv(r'C:\Users\PC\Documents\Learning_PYTHON\data_jobs.csv')
df['job_posted_date'] = pd.to_datetime(df.job_posted_date)

In [3]:
# Accessing the data by row's index and column's index . just by numbers
df.iloc [0:11 , 11:14]

   salary_rate  salary_year_avg  salary_hour_avg
0          NaN              NaN              NaN
1          NaN              NaN              NaN
2          NaN              NaN              NaN
3          NaN              NaN              NaN
4          NaN              NaN              NaN
5          NaN              NaN              NaN
6          NaN              NaN              NaN
7          NaN              NaN              NaN
8          NaN              NaN              NaN
9          NaN              NaN              NaN
10         NaN              NaN              NaN

In [4]:
# Accessing the same data but this time with row's index and column's names
df.loc [ 0:11 , 'salary_rate':'salary_hour_avg']

# Note : the .loc method is showing the last index you wrote too ( in this case you wrote 11 )

   salary_rate  salary_year_avg  salary_hour_avg
0          NaN              NaN              NaN
1          NaN              NaN              NaN
2          NaN              NaN              NaN
3          NaN              NaN              NaN
4          NaN              NaN              NaN
5          NaN              NaN              NaN
6          NaN              NaN              NaN
7          NaN              NaN              NaN
8          NaN              NaN              NaN
9          NaN              NaN              NaN
10         NaN              NaN              NaN
11         NaN              NaN              NaN

In [5]:
# Accessing the data with removing the Nan values 
df.loc [: , 'salary_rate':'salary_hour_avg'].dropna (subset = 'salary_rate')

       salary_rate  salary_year_avg  salary_hour_avg
28            year         109500.0              NaN
43            hour              NaN             97.5
51            hour              NaN             72.5
77            year         140000.0              NaN
92            year         120000.0              NaN
...            ...              ...              ...
785624        year         139216.0              NaN
785641        year         150000.0              NaN
785648        year         221875.0              NaN
785682        year         157500.0              NaN
785692        year         157500.0              NaN

[33067 rows x 3 columns]

In [7]:
df.loc [0:150 , 'job_country':'salary_hour_avg'].dropna(subset='salary_rate')

       job_country salary_rate  salary_year_avg  salary_hour_avg
28      Costa Rica        year         109500.0              NaN
43   United States        hour              NaN             97.5
51   United States        hour              NaN             72.5
77           Sudan        year         140000.0              NaN
92   United States        year         120000.0              NaN
100  United States        year         228222.0              NaN
109  United States        year          89000.0              NaN
116  United States        year         114000.0              NaN
146  United States        year         129500.0              NaN